services:
  - type: web
    name: ericon-rodent-research-and-monitoring-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_URL
        sync: false
