/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { RodentSpecimen } from '../../types';

export const INITIAL_SPECIMENS: RodentSpecimen[] = [
  {
    Record_ID: 'EXP-2026-0001',
    Date_Captured: '28/05/2026',
    Time_Checked: '08:00',
    Location_Name: 'Morogoro_Block_A',
    GPS_Latitude: -6.8231,
    GPS_Longitude: 37.6612,
    EMA_Node_ID: 'EMA-2',
    Species_ID: 'Mastomys natalensis',
    Sex: 'Male',
    Maturity_Stage: 'Adult',
    Reproductive_Condition: 'M: Scrotal',
    Weight_g: 45,
    Head_Body_Length_mm: 120,
    Tail_Length_mm: 105,
    Hind_Foot_mm: 22.1,
    Ear_Length_mm: 17.2,
    Parasite_Load_Ext: 1,
    Ectoparasite_Spp: 'None',
    Ectoparasite_Common_Name: 'None',
    Ectoparasite_Count: 0,
    Endoparasite_Presence: 'No',
    Endoparasite_Spp: 'None',
    Endoparasite_Common_Name: 'None',
    Survival_24H: 'Alive',
    Survival_1WK: 'Alive',
    Survival_2WK: 'Alive',
    Survival_1M: 'Alive',
    Survival_3M: 'Alive',
    Recapture_Status: 'New Capture',
    Time_to_Event_Days: 90,
    Event_Status: 0,
    Trap_Night_ID: 1,
    Experiment_ID: 'EXP-ER-01',
    Team_ID: 'CRME-T1',
    Researcher_ID: 'RES-09',
    Site_Type: 'ERICON Fully Protected Farm',
    Farm_Name: 'Chollima Research Fields',
    Village: 'Morogoro',
    Crop_Type: 'Maize',
    Planting_Date: '2026-04-10',
    Harvest_Date: '2026-06-15',
    Farm_Size_Acre: 5,
    ERICON_Coverage_Pct: 100,
    ERICON_Installed: 'Yes',
    Installation_Date: '2026-04-01',
    Rodent_Sightings: 2,
    Trap_Success_Rate: 4,
    Crop_Attack_Frequency: 'Low',
    Distance_to_Warehouse: 120,
    Irrigation: 'Yes',
    Soil_Type: 'Clay-loam',
    Observation_Date: '2026-05-28',
    Crop_Stage: 'Maturity',
    Rodent_Signs: 'None detected',
    Burrow_Count: 0,
    Trap_Count: 4,
    Rodent_Count: 0,
    Damaged_Plants: 10,
    Total_Plants: 1000,
    Damage_Pct: 1.0,
    Cause: 'Rodent',
    Severity: 'Low',
    Expected_Yield: 5000,
    Actual_Yield: 4950,
    Yield_Loss: 50,
    Economic_Loss: 15.0,
    Storage_Type: 'Silo',
    Protected: 'Yes',
    Rodent_Activity: 'Low',
    Contaminated_Bags: 0,
    Loss_Pct: 0.0
  },
  {
    Record_ID: 'EXP-2026-0002',
    Date_Captured: '28/05/2026',
    Time_Checked: '08:15',
    Location_Name: 'Morogoro_Block_A',
    GPS_Latitude: -6.8233,
    GPS_Longitude: 37.6615,
    EMA_Node_ID: 'EMA-2',
    Species_ID: 'Mastomys natalensis',
    Sex: 'Female',
    Maturity_Stage: 'Adult',
    Reproductive_Condition: 'F: Lactating',
    Weight_g: 48,
    Head_Body_Length_mm: 122,
    Tail_Length_mm: 108,
    Hind_Foot_mm: 22.4,
    Ear_Length_mm: 17.5,
    Parasite_Load_Ext: 2,
    Ectoparasite_Spp: 'None',
    Ectoparasite_Common_Name: 'None',
    Ectoparasite_Count: 0,
    Endoparasite_Presence: 'No',
    Endoparasite_Spp: 'None',
    Endoparasite_Common_Name: 'None',
    Survival_24H: 'Alive',
    Survival_1WK: 'Alive',
    Survival_2WK: 'Alive',
    Survival_1M: 'Alive',
    Survival_3M: 'Alive',
    Recapture_Status: 'New Capture',
    Time_to_Event_Days: 90,
    Event_Status: 0,
    Trap_Night_ID: 1,
    Experiment_ID: 'EXP-ER-02',
    Team_ID: 'CRME-T1',
    Researcher_ID: 'RES-09',
    Site_Type: 'ERICON Semi-Protected Farm',
    Farm_Name: 'Lukobe Outskirts Grid',
    Village: 'Lukobe',
    Crop_Type: 'Maize',
    Planting_Date: '2026-04-10',
    Harvest_Date: '2026-06-15',
    Farm_Size_Acre: 4,
    ERICON_Coverage_Pct: 65,
    Distance_to_Warehouse: 350,
    Irrigation: 'No',
    Soil_Type: 'Sandy-loam',
    Observation_Date: '2026-05-28',
    Crop_Stage: 'Maturity',
    Rodent_Signs: 'Medium active runways',
    Burrow_Count: 6,
    Trap_Count: 8,
    Rodent_Count: 3,
    Damaged_Plants: 120,
    Total_Plants: 1000,
    Damage_Pct: 12.0,
    Cause: 'Rodent',
    Severity: 'Moderate',
    Expected_Yield: 5000,
    Actual_Yield: 4400,
    Yield_Loss: 600,
    Economic_Loss: 180.0,
    Storage_Type: 'Traditional Store',
    Protected: 'No',
    Rodent_Activity: 'Medium',
    Contaminated_Bags: 5,
    Loss_Pct: 1.5
  },
  {
    Record_ID: 'EXP-2026-0003',
    Date_Captured: '28/05/2026',
    Time_Checked: '08:30',
    Location_Name: 'Morogoro_Block_B',
    GPS_Latitude: -6.8251,
    GPS_Longitude: 37.6654,
    EMA_Node_ID: 'EMA-3',
    Species_ID: 'Mastomys natalensis',
    Sex: 'Male',
    Maturity_Stage: 'Sub-Adult',
    Reproductive_Condition: 'M: Non-scrotal',
    Weight_g: 38,
    Head_Body_Length_mm: 110,
    Tail_Length_mm: 98,
    Hind_Foot_mm: 21.0,
    Ear_Length_mm: 16.5,
    Parasite_Load_Ext: 3,
    Ectoparasite_Spp: 'Laelaps echidnina',
    Ectoparasite_Common_Name: 'Spiny rat mite',
    Ectoparasite_Count: 15,
    Endoparasite_Presence: 'Yes',
    Endoparasite_Spp: 'Hymenolepis diminuta',
    Endoparasite_Common_Name: 'Rat tapeworm',
    Survival_24H: 'Dead',
    Survival_1WK: 'Dead',
    Survival_2WK: 'Removed',
    Survival_1M: 'Removed',
    Survival_3M: 'Removed',
    Recapture_Status: 'New Capture',
    Time_to_Event_Days: 6,
    Event_Status: 1,
    Trap_Night_ID: 1,
    Experiment_ID: 'EXP-ER-03',
    Team_ID: 'CRME-T1',
    Researcher_ID: 'RES-09',
    Site_Type: 'Non-ERICON Control Farm',
    Farm_Name: 'Gairo District Control',
    Village: 'Gairo',
    Crop_Type: 'Maize',
    Planting_Date: '2026-04-10',
    Harvest_Date: '2026-06-15',
    Farm_Size_Acre: 6,
    ERICON_Coverage_Pct: 0,
    Distance_to_Warehouse: 400,
    Irrigation: 'No',
    Soil_Type: 'Silt',
    Observation_Date: '2026-05-28',
    Crop_Stage: 'Maturity',
    Rodent_Signs: 'Heavy burrow clustering, intense plant biting',
    Burrow_Count: 22,
    Trap_Count: 12,
    Rodent_Count: 8,
    Damaged_Plants: 286,
    Total_Plants: 1000,
    Damage_Pct: 28.6,
    Cause: 'Rodent',
    Severity: 'Severe',
    Expected_Yield: 5000,
    Actual_Yield: 3200,
    Yield_Loss: 1800,
    Economic_Loss: 540.0,
    Storage_Type: 'Traditional Store',
    Protected: 'No',
    Rodent_Activity: 'High',
    Contaminated_Bags: 18,
    Loss_Pct: 5.4
  },
  {
    Record_ID: 'EXP-2026-0004',
    Date_Captured: '29/05/2026',
    Time_Checked: '07:45',
    Location_Name: 'Morogoro_Block_B',
    GPS_Latitude: -6.8253,
    GPS_Longitude: 37.6657,
    EMA_Node_ID: 'EMA-3',
    Species_ID: 'Rattus rattus',
    Sex: 'Female',
    Maturity_Stage: 'Adult',
    Reproductive_Condition: 'F: Pregnant',
    Weight_g: 135,
    Head_Body_Length_mm: 175,
    Tail_Length_mm: 190,
    Hind_Foot_mm: 30.5,
    Ear_Length_mm: 20.2,
    Parasite_Load_Ext: 1,
    Ectoparasite_Spp: 'Xenopsylla cheopis',
    Ectoparasite_Common_Name: 'Oriental rat flea',
    Ectoparasite_Count: 4,
    Endoparasite_Presence: 'Yes',
    Endoparasite_Spp: 'Capillaria hepatica',
    Endoparasite_Common_Name: 'Liver threadworm',
    Survival_24H: 'Alive',
    Survival_1WK: 'Alive',
    Survival_2WK: 'Alive',
    Survival_1M: 'Alive',
    Survival_3M: 'Alive',
    Recapture_Status: 'Recapture-Tagged',
    Time_to_Event_Days: 90,
    Event_Status: 0,
    Trap_Night_ID: 2,
    Experiment_ID: 'EXP-ER-01',
    Team_ID: 'CRME-T1',
    Researcher_ID: 'RES-09',
    Site_Type: 'ERICON Fully Protected Farm',
    Farm_Name: 'Chollima Research Fields',
    Village: 'Morogoro',
    Crop_Type: 'Maize',
    Planting_Date: '2026-04-10',
    Harvest_Date: '2026-06-15',
    Farm_Size_Acre: 5,
    ERICON_Coverage_Pct: 100,
    Distance_to_Warehouse: 120,
    Irrigation: 'Yes',
    Soil_Type: 'Clay-loam',
    Observation_Date: '2026-05-29',
    Crop_Stage: 'Maturity',
    Burrow_Count: 1,
    Trap_Count: 4,
    Rodent_Count: 0,
    Damaged_Plants: 8,
    Total_Plants: 1000,
    Damage_Pct: 0.8,
    Expected_Yield: 5000,
    Actual_Yield: 4970,
    Yield_Loss: 30,
    Economic_Loss: 9.0,
    Storage_Type: 'Silo',
    Protected: 'Yes',
    Rodent_Activity: 'Low',
    Contaminated_Bags: 0,
    Loss_Pct: 0.0
  },
  {
    Record_ID: 'EXP-2026-0005',
    Date_Captured: '29/05/2026',
    Time_Checked: '08:10',
    Location_Name: 'Morogoro_Block_C',
    GPS_Latitude: -6.8274,
    GPS_Longitude: 37.6698,
    EMA_Node_ID: 'EMA-4',
    Species_ID: 'Mus musculus',
    Sex: 'Male',
    Maturity_Stage: 'Juvenile',
    Reproductive_Condition: 'M: Non-scrotal',
    Weight_g: 17,
    Head_Body_Length_mm: 72,
    Tail_Length_mm: 68,
    Hind_Foot_mm: 15.2,
    Ear_Length_mm: 12.0,
    Parasite_Load_Ext: 0,
    Ectoparasite_Spp: 'None',
    Ectoparasite_Common_Name: 'None',
    Ectoparasite_Count: 0,
    Endoparasite_Presence: 'No',
    Endoparasite_Spp: 'None',
    Endoparasite_Common_Name: 'None',
    Survival_24H: 'Alive',
    Survival_1WK: 'Alive',
    Survival_2WK: 'Alive',
    Survival_1M: 'Alive',
    Survival_3M: 'Alive',
    Recapture_Status: 'New Capture',
    Time_to_Event_Days: 90,
    Event_Status: 0,
    Trap_Night_ID: 2,
    Experiment_ID: 'EXP-ER-02',
    Team_ID: 'CRME-T1',
    Researcher_ID: 'RES-09',
    Site_Type: 'ERICON Semi-Protected Farm',
    Farm_Name: 'Lukobe Outskirts Grid',
    Village: 'Lukobe',
    Crop_Type: 'Maize',
    Planting_Date: '2026-04-10',
    Harvest_Date: '2026-06-15',
    Farm_Size_Acre: 4,
    ERICON_Coverage_Pct: 65,
    Distance_to_Warehouse: 350,
    Irrigation: 'No',
    Soil_Type: 'Sandy-loam',
    Observation_Date: '2026-05-29',
    Crop_Stage: 'Maturity',
    Burrow_Count: 5,
    Trap_Count: 8,
    Rodent_Count: 2,
    Damaged_Plants: 110,
    Total_Plants: 1000,
    Damage_Pct: 11.0,
    Expected_Yield: 5000,
    Actual_Yield: 4450,
    Yield_Loss: 550,
    Economic_Loss: 165.0,
    Storage_Type: 'Traditional Store',
    Protected: 'No',
    Rodent_Activity: 'Medium',
    Contaminated_Bags: 4,
    Loss_Pct: 1.2
  }
];
